name: Build Game
on: workflow_dispatch
jobs:
  buid:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install build tool
        run: npm i -g scratch3-builder
      - name: Run build tool
        run: sf-make
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: |
            *.html     